#!/usr/bin/env python3
"""Write outputs/tables/macros.tex from the generated facts files.

Every number quoted in the prose of the paper comes from a macro
defined here. Macro names use letters only, as LaTeX requires.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLISHED = ROOT / "experiments" / "processed" / "published_repeats" / "facts.json"
REPEATS = ROOT / "experiments" / "processed" / "sembench_repeats" / "facts.json"
OUT = ROOT / "outputs" / "tables" / "macros.tex"
PROCESSED = ROOT / "experiments" / "processed"
MACRO_FILES = [
    PROCESSED / "sembench_repeats" / "boost.json",
    PROCESSED / "sembench_repeats" / "margin_noise_macros.json",
    PROCESSED / "campaigns_macros.json",
    PROCESSED / "controls" / "temperature.json",
    PROCESSED / "controls" / "divergence.json",
    PROCESSED / "controls" / "probes.json",
    PROCESSED / "commercial.json",
    PROCESSED / "claims.json",
    PROCESSED / "uda_lineage.json",
    PROCESSED / "exposure.json",
    PROCESSED / "published_engines.json",
    PROCESSED / "more_executions.json",
    PROCESSED / "lrobench_failures.json",
]
MODEL_MACRO = {
    "managed-gpt-oss-120b": "Gptoss",
    "managed-llama-3-3-70b-instruct": "LlamaW",
    "vllm-llama-3-3-70b-instruct": "LlamaR",
    "vllm-qwen2-5-72b-instruct": "Qwen",
    "managed-mistral-small-3-1-24b-2503": "Mistral",
    "vllm-granite-3-3-8b-instruct": "Granite",
}


def pct(value: float, digits: int = 1) -> str:
    return "--" if value != value else f"{100 * value:.{digits}f}\\%"


def main() -> None:
    lines = [
        "% Generated by scripts/paper_macros.py. Do not edit by hand.",
        "\\providecommand{\\pending}[1]{\\textcolor{red}{[pending#1]}}",
    ]

    defined: set[str] = set()

    def define(name: str, value) -> None:
        if name in defined:
            raise SystemExit(f"macro defined twice: {name}")
        defined.add(name)
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    if PUBLISHED.exists():
        facts = json.loads(PUBLISHED.read_text())
        define("pubCells", facts["cells"])
        define("pubCellsMoving", facts["cells_moving"])
        define("pubCellsMovingPct", pct(facts["cells_moving"] / facts["cells"], 0))
        define("pubCellsBig", facts["cells_range_01"])
        define("pubCellsBigPct", pct(facts["cells_range_01"] / facts["cells"], 0))
        define("pubPairs", facts["pairs_untied"])
        define("pubPairsReversed", facts["pairs_any_reversal"])
        define("pubPairsReversedPct", pct(facts["pairs_any_reversal"] / facts["pairs_untied"], 0))
        define("pubRuns", facts["single_runs"])
        define("pubRunsReversing", facts["single_runs_reversing"])
        define("pubRunsReversingPct", pct(facts["single_runs_reversing"] / facts["single_runs"], 1))
        define("pubEmptyCells", facts["cells_with_empty_runs"])
        define("pubCleanCellsMovingPct", pct(facts["clean_cells_moving"] / facts["clean_cells"], 0))
        define("pubCleanCellsBigPct", pct(facts["clean_cells_range_01"] / facts["clean_cells"], 0))
        rankings = facts["scenario_rankings"]
        define("pubScenarios", len(rankings))
        define("pubWinnerStable", sum(row["same_winner"] == row["repeats"] for row in rankings))
        define("pubOrderRuns", sum(row["repeats"] for row in rankings))
        define("pubOrderSame", sum(row["same_order"] for row in rankings))
        everything = facts["all_configs"]
        define("pubAllCells", everything["cells"])
        define("pubAllCellsMovingPct", pct(everything["cells_moving"] / everything["cells"], 0))
        define("pubAllPairsReversedPct", pct(everything["pairs_any_reversal"] / everything["pairs_untied"], 0))
        text = facts["text"]
        define("pubTextCells", text["cells"])
        define("pubTextQueries", text["queries"])
        define("pubTextCellsMoving", text["cells_moving"])
        define("pubTextCellsMovingPct", pct(text["cells_moving"] / text["cells"], 0))
        define("pubTextCellsBig", text["cells_range_01"])
        define("pubTextMaxRange", f"{text['max_range']:.2f}")
        define("pubTextPairs", text["pairs_untied"])
        define("pubTextPairsReversed", text["pairs_any_reversal"])
        define("pubTextPairsReversedPct", pct(text["pairs_any_reversal"] / text["pairs_untied"], 0))
        for scenario, counts in text["by_scenario"].items():
            name = {"ecomm": "Ecomm", "mmqa": "Mmqa"}.get(scenario, scenario.capitalize())
            define(f"pubText{name}Cells", counts["cells"])
            define(f"pubText{name}Moving", counts["cells_moving"])

    if REPEATS.exists():
        facts = json.loads(REPEATS.read_text())
        for model, values in facts["models"].items():
            prefix = MODEL_MACRO[model]
            define(f"flip{prefix}", pct(values["flip_rate"], 2 if values["flip_rate"] < 0.01 else 1))
            low, high = values["flip_ci"]
            define(f"flipCi{prefix}", f"[{pct(low, 2)}, {pct(high, 2)}]")
            define(f"items{prefix}", f"{values['items']:,}".replace(",", "{,}"))
            define(f"flipped{prefix}", values["flipped"])
            define(f"notReproduced{prefix}", values["queries_not_reproduced"])
            define(f"queries{prefix}", values["queries"])
            define(f"flipAllRuns{prefix}", pct(values["flip_rate_all_runs"], 2 if values["flip_rate_all_runs"] < 0.01 else 1))
            define(f"flipMacro{prefix}", pct(values["flip_rate_macro"], 2 if values["flip_rate_macro"] < 0.01 else 1))
            define(f"disagree{prefix}", pct(values["pair_disagreement"], 2))
            auc = values.get("margin_auc")
            if auc is not None and not (isinstance(auc, float) and math.isnan(auc)):
                define(f"marginAuc{prefix}", f"{auc:.2f}")
                low, high = values["margin_auc_ci"]
                define(f"marginAucCi{prefix}", f"[{low:.2f}, {high:.2f}]")
                define(f"marginFlipped{prefix}", values["margin_flipped"])
            if "reasoning_chars_flipped" in values:
                define(f"reasonFlipped{prefix}", f"{values['reasoning_chars_flipped']:.0f}")
                define(f"reasonStable{prefix}", f"{values['reasoning_chars_stable']:.0f}")
            if "reasoning_auc" in values:
                define(f"reasonAuc{prefix}", f"{values['reasoning_auc']:.2f}")
                low, high = values["reasoning_auc_ci"]
                define(f"reasonAucCi{prefix}", f"[{low:.2f}, {high:.2f}]")
                define(f"reasonAucWithin{prefix}", f"{values['reasoning_auc_within']:.2f}")
                define(f"reasonAucWithinMin{prefix}", f"{values['reasoning_auc_within_min']:.2f}")
                define(f"reasonAucWithinMax{prefix}", f"{values['reasoning_auc_within_max']:.2f}")
                define(f"reasonAucQueries{prefix}", values["reasoning_auc_queries"])
                define(f"reasonAucFlipped{prefix}", f"{values['reasoning_flipped']:,}".replace(",", "{,}"))
        for model, prefix in MODEL_MACRO.items():
            if model not in facts["models"]:
                for stem in ("flip", "flipCi", "items", "flipped", "notReproduced", "queries"):
                    define(f"{stem}{prefix}", "\\pending{}")
        cross = facts["cross_model"]
        if cross["flipped_items"] and cross["stable_items"]:
            define("contestedFlipped", pct(cross["flipped_items_cross_model_disagree"] / cross["flipped_items"], 0))
            define("contestedStable", pct(cross["stable_items_cross_model_disagree"] / cross["stable_items"], 0))
        for model, values in facts["models"].items():
            define(f"marginItems{MODEL_MACRO[model]}", values["margin_items"])
        stacks = facts["stacks"]
        if stacks["items"]:
            define("stackItems", f"{stacks['items']:,}".replace(",", "{,}"))
            define("stackDiffer", stacks["majority_differs"])
            define("stackDifferPct", pct(stacks["majority_differs"] / stacks["items"], 1))
            define("stackFlip", stacks["flipped_either"])
            define("stackFlipPct", pct(stacks["flipped_either"] / stacks["items"], 1))
            for scenario, counts in stacks.get("by_scenario", {}).items():
                name = scenario.capitalize()
                define(f"stackItems{name}", f"{counts['items']:,}".replace(",", "{,}"))
                define(f"stackDiffer{name}", counts["majority_differs"])
                define(f"stackDifferPct{name}", pct(counts["majority_differs"] / counts["items"], 1))
                define(f"stackFlip{name}", counts["flipped_either"])
                define(f"stackFlipPct{name}", pct(counts["flipped_either"] / counts["items"], 1))
        reversals = facts["model_reversals"]
        define("modelPairs", reversals["pairs"])
        define("modelPairsReversed", reversals["pairs_reversed"])
        define("modelPairsReversedPct", pct(reversals["pairs_reversed"] / reversals["pairs"], 0))
        define("modelDrawsReversedPct", pct(reversals["draws_reversed"] / reversals["draws"], 1))
        if facts["concentration"]:
            define("topRunShare", pct(facts["concentration"][0]["top_run_share"], 0))
        define("correlatedCells", len(facts["correlated_cells"]))
        words_k = {2: "Two", 3: "Three", 5: "Five", 10: "Ten"}
        for k, rate in facts["flip_by_k"]["rates"].items():
            if int(k) in words_k:
                define(f"flipK{words_k[int(k)]}", pct(rate, 1))
        heldout = facts.get("heldout", [])
        if heldout:
            define("heldoutQueries", len(heldout))
            define("heldoutWithin", sum(abs(row["predicted"] - row["measured"]) <= 0.15 for row in heldout))
            define("heldoutMaxErr", f"{facts['heldout_max_abs_error']:.1f}")
            worst = max(heldout, key=lambda row: abs(row["predicted"] - row["measured"]))
            define("heldoutWorstPred", f"{worst['predicted']:.2f}")
            define("heldoutWorstMeas", f"{worst['measured']:.2f}")
        numbers = ["Zero", "One", "Two", "Three", "Four", "Five"]
        for row in facts.get("dissent", []):
            if row["items"] >= 20:
                rate = row["flipped"] / row["items"]
                define(f"dissent{numbers[row['dissent']]}{MODEL_MACRO[row['model']]}", pct(rate, 2 if rate < 0.01 else 1))
        words = {"bool": "Bool", "label": "Label", "score": "Score", "extract": "Extract", "movie": "Movie", "medical": "Medical"}
        for row in facts["groups"]:
            prefix = MODEL_MACRO[row["model"]]
            define(f"flip{words[row['group']]}{prefix}", pct(row["flip_rate"], 2 if row["flip_rate"] < 0.01 else 1))

    REMEDY = ROOT / "experiments" / "processed" / "sembench_repeats" / "remedies_facts.json"
    if REMEDY.exists():
        facts = json.loads(REMEDY.read_text())
        if facts.get("cells"):
            define("voteThreeReduction", pct(facts["mean_reduction_vote3"], 0))
            define("voteFiveReduction", pct(facts["mean_reduction_vote5"], 0))
            define("minorityHeavy", pct(facts["minority_at_least_3_overall"], 0))
            define("voteThreeMaxCost", f"{facts['max_vote3_cost']:.2f}")
            if facts.get("max_accuracy_change") is not None:
                define("voteMaxAccuracyChange", f"{100 * facts['max_accuracy_change']:.1f}")

    PROBES = ROOT / "experiments" / "processed" / "sembench_repeats" / "probes.json"
    if PROBES.exists():
        probes = json.loads(PROBES.read_text())
        compared = [entry for entry in probes if "difference_ci" in entry]
        define("probeSettings", len(compared))
        define("probeNull", sum(low <= 0 <= high for low, high in (entry["difference_ci"] for entry in compared)))
        names = {
            "w1_lp_probe": "ConcOne",
            "w8_lp_probe": "ConcEight",
            "w20_lp_probe": "ConcTwenty",
            "w64_lp_probe": "ConcSixtyFour",
            "w20_shuffle_lp_probe": "Shuffle",
            "w20_r-low_probe": "EffortLow",
            "w20_r-medium_probe": "EffortMedium",
            "w20_r-high_probe": "EffortHigh",
        }
        query_words = {"3": "Three", "8": "Eight", "9": "Nine"}
        for entry in probes:
            name = names[entry["setting"]]
            for query, values in entry["queries"].items():
                word = query_words[str(query)]
                define(f"probe{name}Disagree{word}", pct(values["pair_disagreement"], 2))
                if values["majority_moved"] is not None:
                    define(f"probe{name}Moved{word}", pct(values["majority_moved"], 1))
                define(f"probe{name}Repro{word}", f"{values['answer_reproduction']:.2f}")

    CASCADE = ROOT / "experiments" / "processed" / "sembench_repeats" / "cascade.json"
    if CASCADE.exists():
        oracle_names = {"gpt-oss-120B": "Gptoss", "Llama-70B (M)": "LlamaW"}
        for entry in json.loads(CASCADE.read_text()):
            name = entry["query"].replace("Medical Q1", "MedOne").replace("Medical Q4", "MedFour") + oracle_names[entry["oracle"]]
            define(f"casRepro{name}", pct(entry["recall_reproduction"], 0))
            define(f"casSame{name}", pct(entry["recall_violation_same"], 1))
            define(f"casOther{name}", pct(entry["recall_violation_other"], 1))
            define(f"casRows{name}", f"{entry['recall_returned']:.0f}")
            define(f"casDis{name}", pct(entry["oracle_disagreement"], 1))
        define("casItems", json.loads(CASCADE.read_text())[0]["items"])

    AMPLIFICATION = ROOT / "experiments" / "processed" / "sembench_repeats" / "amplification.json"
    if AMPLIFICATION.exists():
        amplification = json.loads(AMPLIFICATION.read_text())
        define("ampEveryCells", amplification["every_item_cells"])
        define("ampEveryWithin", amplification["every_item_within_015"])
        define("ampEveryMae", f"{amplification['every_item_mean_abs_error']:.2f}")
        define("ampOtherCells", amplification["other_cells"])
        define("ampOtherAbove", amplification["other_above_curve"])
        curves = amplification["flip_by_k_by_kind"]
        define("flipKTwoScore", pct(curves["score"]["2"] / 100, 1))
        define("flipKTenScore", pct(curves["score"]["10"] / 100, 1))
        define("flipKTwoBool", pct(curves["bool"]["2"] / 100, 1))
        define("flipKTenBool", pct(curves["bool"]["10"] / 100, 1))

    DUPLICATES = ROOT / "experiments" / "processed" / "sembench_repeats" / "duplicates.json"
    if DUPLICATES.exists():
        duplicates = json.loads(DUPLICATES.read_text())
        example = duplicates.pop("example")
        define("dupExampleDiffer", example["copies_differ"])
        define("dupExampleRuns", example["executions"])
        define("dupAnyWithinGptoss", example["reference_inputs_any_within"])
        define("dupInputs", duplicates["managed-gpt-oss-120b"]["duplicated_inputs"])
        for model, suffix in MODEL_MACRO.items():
            if model in duplicates:
                entry = duplicates[model]
                define(f"dupWithin{suffix}", pct(entry["within"], 1 if entry["within"] >= 0.01 else 2))
                define(f"dupAcross{suffix}", pct(entry["across"], 1 if entry["across"] >= 0.01 else 2))
                low, high = entry["within_ci"]
                define(f"dupWithinCi{suffix}", f"{100 * low:.1f}--{100 * high:.1f}\\%")

    SELECTIVE = ROOT / "experiments" / "processed" / "sembench_repeats" / "selective_vote.json"
    if SELECTIVE.exists():
        selective = json.loads(SELECTIVE.read_text())
        removed, of_full = selective["share_removed"], selective["share_of_full_vote"]
        define("selRemovedFull", pct(removed["vote3"], 0))
        for share, word in (("0.1", "Ten"), ("0.2", "Twenty"), ("0.3", "Thirty")):
            define(f"selOfFull{word}", pct(of_full[f"longest_{share}"], 0))
            define(f"selRandomOfFull{word}", pct(of_full[f"random_{share}"], 0))

    BOUNDS = ROOT / "experiments" / "processed" / "sembench_repeats" / "answer_bounds.json"
    if BOUNDS.exists():
        bounds = json.loads(BOUNDS.read_text())
        count = bounds["count"]
        define("bndLow", count["low"])
        define("bndHigh", count["high"])
        define("bndLater", len(count["later"]))
        define("bndLaterInside", count["later_inside"])
        define("bndLaterCounts", ", ".join(str(value) for value in count["later"]))
        define("bndGold", count["gold"])
        for entry in bounds["sets"]:
            name = {("medical", 1): "MedOne", ("movie", 7): "QSeven"}[(entry["scenario"], entry["query"])]
            define(f"bnd{name}Certain", entry["certain"])
            define(f"bnd{name}Possible", entry["possible"])
            define(f"bnd{name}Answer", f"{entry['mean_answer']:.0f}")
            define(f"bnd{name}Bracketed", entry["bracketed"])
            define(f"bnd{name}Missing", f"{entry['mean_certain_missing']:.1f}")
            define(f"bnd{name}Outside", f"{entry['mean_outside_possible']:.1f}")

    LADDER = ROOT / "experiments" / "processed" / "ladder.json"
    if LADDER.exists():
        ladder = json.loads(LADDER.read_text())
        pooled = ladder["pooled"]
        uda_quality = [entry["quality"] for entry in ladder["suites"]["udabench"].values()]
        define("ladderUdaQualMin", pct(min(uda_quality), 0))
        define("ladderUdaQualMax", pct(max(uda_quality), 0))
        for suite, prefix in (("sembench", "Sem"), ("lrobench", "Lro"), ("udabench", "Uda")):
            for level, suffix in (("outputs", "Out"), ("answer", "Ans"), ("quality", "Qual")):
                if pooled[suite].get(level) is not None:
                    define(f"ladder{prefix}{suffix}", pct(pooled[suite][level], 0))

    NEEDED = ROOT / "experiments" / "processed" / "runs_needed.json"
    if NEEDED.exists():
        needed = json.loads(NEEDED.read_text())
        for population, name in (("published_text", "Pub"), ("deployments", "Dep")):
            values = needed[population]
            define(f"need{name}Pairs", values["pairs"])
            define(f"need{name}MoreOne", values["pairs_needing_more_than_one"])
            define(f"need{name}MoreFive", values["pairs_needing_more_than_five"])
            define(f"need{name}MoreTen", values["pairs_needing_more_than_ten"])
            define(f"need{name}Median", f"{values['median_when_more_than_one']:.0f}")

    SUITES = ROOT / "experiments" / "processed" / "text_suites_facts.json"
    if SUITES.exists():
        suites = json.loads(SUITES.read_text())
        for model, values in suites["lro"].items():
            prefix = MODEL_MACRO[model]
            define(f"lroQueries{prefix}", values["queries"])
            define(f"lroFail{prefix}", values["queries_any_failure"])
            define(f"lroFailPct{prefix}", pct(values["queries_any_failure"] / values["queries"], 0))
            define(f"lroMixedFail{prefix}", values["queries_mixed_failure"])
            define(f"lroAnswered{prefix}", values["answered_queries"])
            define(f"lroDiffer{prefix}", values["answers_differ"])
            define(f"lroDifferPct{prefix}", pct(values["answers_differ"] / values["answered_queries"], 0))
            define(f"lroMoves{prefix}", values["quality_moves"])
            define(f"lroRange{prefix}", f"{values['mean_quality_range']:.3f}")
            define(f"lroRuns{prefix}", f"{values['runs']:,}".replace(",", "{,}"))
            define(f"lroFailedRuns{prefix}", f"{values['failed_runs']:,}".replace(",", "{,}"))
        define("lroSettings", suites["lro_settings"])
        for model, values in suites["lro_setting_range"].items():
            define(f"lroSettingMinPct{MODEL_MACRO[model]}", pct(values["min"], 0))
            define(f"lroSettingMaxPct{MODEL_MACRO[model]}", pct(values["max"], 0))
        for key, values in suites["lro_by_operator"].items():
            model, operator = key.split("|")
            if values["answered_queries"]:
                define(f"lroDifferPct{operator.capitalize()}{MODEL_MACRO[model]}",
                       pct(values["answers_differ"] / values["answered_queries"], 0))
        for model, values in suites["uda"].items():
            prefix = MODEL_MACRO[model]
            define(f"udaValueFlipPct{prefix}", pct(values["item_flip_rate"], 1))
            define(f"udaNullShare{prefix}", pct(values["null_flip_share"], 0))
            define(f"udaValueToValue{prefix}", pct(values["value_to_value_flip_rate"], 1))
            define(f"udaValueFlips{prefix}", values["item_flips"])
            define(f"udaValues{prefix}", f"{values['items']:,}".replace(",", "{,}"))
            define(f"udaDiffer{prefix}", values["answers_differ"])
            define(f"udaDifferPct{prefix}", pct(values["answers_differ"] / values["queries"], 0))
            define(f"udaMoves{prefix}", values["quality_moves"])
            define(f"udaScored{prefix}", values["scored_queries"])
            define(f"udaMeanFOne{prefix}", f"{values['mean_f1']:.2f}")
            define(f"udaRange{prefix}", f"{values['mean_f1_range']:.3f}")
            define(f"udaMaxRange{prefix}", f"{values['max_f1_range']:.2f}")
            for task, count in values["differ_by_task"].items():
                define(f"udaDiffer{task}{prefix}", count)
        define("udaQueries", sum(suites["uda_tasks"].values()))
        define("udaGoldEmpty", suites["uda_gold_empty"])
        for task, count in suites["uda_tasks"].items():
            define(f"udaTask{task}", count)
        for row in suites["product"]:
            name = "".join(part.capitalize() for part in row["task"].split("_"))
            define(f"prodFlip{name}", pct(row["flips"] / row["items"], 0))
            define(f"prodOutputs{name}", row["outputs"])

    QUERIES = ROOT / "experiments" / "processed" / "sembench_repeats" / "queries.csv"
    if QUERIES.exists():
        import csv

        lines.append("\\newcommand{\\cellval}[4]{\\csname cell@#1@#2@#3@#4\\endcsname}")
        with QUERIES.open(newline="", encoding="utf-8") as handle:
            for row in csv.DictReader(handle):
                if row["model"] not in MODEL_MACRO or row["setting"] not in (
                        "w20", "w20_lp", "w20_exact_join40", "w20_lp_exact_join40"):
                    continue
                quality = json.loads(row["quality_values"]) if row["quality_values"] else []
                values = {
                    "k": row["repeats"],
                    "items": row["items"],
                    "flip": pct(float(row["item_flip_rate_k5"]), 1),
                    "repro": f"{float(row['answer_reproduction']):.2f}",
                    "indep": f"{float(row['answer_reproduction_independent']):.2f}",
                    "distinct": row["distinct_answers"],
                    "qmin": f"{min(quality):.2f}" if quality else "--",
                    "qmax": f"{max(quality):.2f}" if quality else "--",
                    "qrange": f"{max(quality) - min(quality):.2f}" if quality else "--",
                }
                for field, value in values.items():
                    name = f"cell@{row['scenario']}@{row['query_id']}@{MODEL_MACRO[row['model']]}@{field}"
                    lines.append(f"\\expandafter\\def\\csname {name}\\endcsname{{{value}}}")

    # Analyses that write their own macro map under the key "macros".
    for path in dict.fromkeys(MACRO_FILES):
        if path.exists():
            for name, value in json.loads(path.read_text()).get("macros", {}).items():
                define(name, value)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(lines) - 1} macros -> {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
