#!/usr/bin/env python3
"""Repetition-based remedies replayed on recorded repeats, without new calls.

For every (scenario, model, setting, query) with at least ten clean repeats,
the repeats are split into disjoint groups and each group is combined into one
answer:

  single       one run per group of one
  vote3        item-wise majority (median for scores) of three runs; identical to
               "run twice, re-ask a third time only where the two disagree"
  vote5        item-wise majority (median for scores) of five runs

For each remedy we report the pairwise item disagreement and the answer reproduction rate
between the combined runs, the item accuracy against SemBench's labels where
the item has one, and the cost in model calls per item. For vote3 the cost is
the arbitrated cost 2 + p, with p the measured share of items on which the
first two runs disagree.

Output: experiments/processed/sembench_repeats/remedies.csv
"""

from __future__ import annotations

import csv
import json
import statistics
import sys
from collections import Counter, defaultdict
from itertools import combinations
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import analyze_sembench_repeats as base  # noqa: E402

ROOT = base.ROOT
OUT = base.PROCESSED / "remedies.csv"
MIN_REPEATS = 10
REMEDIES = {"single": 1, "vote3": 3, "vote5": 5}


def movie_labels() -> dict[str, tuple[str, float | None]]:
    labels = {}
    with base.REVIEWS.open(newline="", encoding="utf-8") as handle:
        for row in csv.DictReader(handle):
            score = None
            raw = (row.get("originalScore") or "").split("/")
            try:
                score = float(raw[0])
            except ValueError:
                pass
            labels[" ".join(row["reviewText"].split())[:120]] = (row["scoreSentiment"], score)
    return labels


def truth(kind: str, query: int, record: dict, labels) -> object:
    """SemBench's label for one Movie item, or None when it has none."""
    label = labels.get(base.review_prefix(record.get("text", "")))
    if label is None:
        return None
    sentiment, score = label
    if kind == "bool" and query in (3, 4):
        return sentiment == "POSITIVE"
    if kind == "label":
        return sentiment
    if kind == "score" and query == 9 and score is not None:
        return score
    return None


def combine(kind: str, values: list) -> object:
    present = [value for value in values if value is not None]
    if not present:
        return None
    if kind == "score":
        return statistics.median_low(sorted(present))
    counts = Counter(present).most_common()
    if len(counts) > 1 and counts[0][1] == counts[1][1]:
        return values[0]
    return counts[0][0]


MINORITY: dict[tuple, dict[int, int]] = {}
TABLE = ROOT / "outputs" / "tables" / "remedies.tex"
FACTS = base.PROCESSED / "remedies_facts.json"
NAMES = {
    ("movie", 1): "Movie Q1",
    ("movie", 2): "Movie Q2",
    ("movie", 3): "Movie Q3",
    ("movie", 4): "Movie Q4",
    ("movie", 8): "Movie Q8",
    ("movie", 9): "Movie Q9",
    ("movie", 10): "Movie Q10",
    ("medical", 1): "Medical Q1",
    ("medical", 4): "Medical Q4",
    ("medical", 10): "Medical Q10",
}


def write_outputs(rows: list[dict]) -> None:
    by_cell = defaultdict(dict)
    for row in rows:
        by_cell[(row["scenario"], row["query_id"], row["model"], row["setting"])][row["remedy"]] = row
    lines = [
        "% Generated by scripts/remedies_sembench_repeats.py. Do not edit by hand.",
        "\\begin{table}[t]",
        "\\caption{Repetition replayed on ten executions of gpt-oss-120B. Disagreement is the probability that two combined "
        "executions differ on an item (\\%). Vote of 3 costs $2+p$ calls per item when the third call is made only where "
        "the first two disagree. Ten executions form only two groups of five, so Vote 5 rests on a single pair and can "
        "exceed Vote 3. Minority $\\ge 3$ is the share of changing items whose less common output occurs in at "
        "least three of the ten executions, so that a vote of three often still returns it.}",
        "\\label{tab:remedies}",
        "\\small",
        "\\begin{tabular}{@{}lrrrrr@{}}",
        "\\toprule",
        "Query & One & Vote 3 & Vote 5 & Cost of 3 & Minority $\\ge 3$ \\\\",
        "\\midrule",
    ]
    facts = {"cells": []}
    for (scenario, query, model, setting), remedies in sorted(by_cell.items(), key=lambda item: (item[0][0] != "movie", item[0][1])):
        if model != "managed-gpt-oss-120b" or setting not in ("w20", "w20_lp") or set(remedies) != set(REMEDIES):
            continue
        minority = MINORITY.get((scenario, model, setting, query), {})
        flipped = sum(minority.values())
        heavy = sum(count for share, count in minority.items() if share >= 3) / flipped if flipped else 0.0
        values = [100 * remedies[name]["item_disagreement"] for name in REMEDIES]
        lines.append(
            f"{NAMES[(scenario, query)]} & " + " & ".join(f"{value:.1f}" for value in values)
            + f" & {remedies['vote3']['calls_per_item']:.2f} & {100 * heavy:.0f}\\% \\\\"
        )
        facts["cells"].append(
            {
                "scenario": scenario,
                "query": query,
                "disagreement": dict(zip(REMEDIES, values)),
                "vote3_cost": remedies["vote3"]["calls_per_item"],
                "minority": minority,
                "minority_at_least_3": heavy,
                "accuracy": {name: remedies[name]["item_accuracy"] for name in REMEDIES},
            }
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    TABLE.write_text("\n".join(lines), encoding="utf-8")
    cells = facts["cells"]
    if cells:
        facts["mean_reduction_vote3"] = statistics.fmean(
            1 - cell["disagreement"]["vote3"] / cell["disagreement"]["single"] for cell in cells if cell["disagreement"]["single"]
        )
        facts["mean_reduction_vote5"] = statistics.fmean(
            1 - cell["disagreement"]["vote5"] / cell["disagreement"]["single"] for cell in cells if cell["disagreement"]["single"]
        )
        total = Counter()
        for cell in cells:
            total.update({int(share): count for share, count in cell["minority"].items()})
        flipped = sum(total.values())
        facts["minority_at_least_3_overall"] = sum(count for share, count in total.items() if share >= 3) / flipped
        facts["max_vote3_cost"] = max(cell["vote3_cost"] for cell in cells)
        changes = [
            abs(cell["accuracy"][name] - cell["accuracy"]["single"])
            for cell in cells
            if cell["accuracy"]["single"] != ""
            for name in ("vote3", "vote5")
        ]
        facts["max_accuracy_change"] = max(changes) if changes else None
    FACTS.write_text(json.dumps(facts, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    labels = movie_labels()
    cells = defaultdict(list)
    for metrics in sorted(base.RAW.glob("*/*/*/repeat-*/Q*.metrics.json")):
        meta = json.loads(metrics.read_text())
        if meta.get("call_errors") or meta.get("status") != "success":
            continue
        query = int(metrics.name.split(".")[0][1:])
        repeat_dir = metrics.parent
        scenario = repeat_dir.parents[2].name
        cells[(scenario, repeat_dir.parents[1].name, repeat_dir.parent.name, query)].append(repeat_dir)

    rows = []
    for (scenario, model, setting, query), dirs in sorted(cells.items()):
        if scenario not in base.KINDS or query not in base.KINDS[scenario] or len(dirs) < MIN_REPEATS:
            continue
        kind, plan = base.KINDS[scenario][query]
        dirs = sorted(dirs, key=lambda path: int(path.name.split("-")[1]))[:MIN_REPEATS]
        runs = [base.read_calls(path / f"Q{query}.calls.jsonl", kind) for path in dirs]
        order = [key for key, _value, _record in runs[0]]
        records = {key: record for key, _value, record in runs[0]}
        per_run = [{key: value for key, value, _record in calls} for calls in runs]
        keys = [key for key in order if all(key in run for run in per_run)]

        groups = None
        if plan == "group_mean_rank":
            prefixes = base.movie_of_items()
            groups = {key: prefixes.get(base.review_prefix(records[key].get("text", ""))) for key in keys}
            groups = {key: value for key, value in groups.items() if value}
        if plan == "mean_of_attribute":
            groups = dict(zip(order, base.medical_q4_ages()))

        gold = {}
        if scenario == "movie":
            for key in keys:
                value = truth(kind, query, records[key], labels)
                if value is not None:
                    gold[key] = value

        for remedy, size in REMEDIES.items():
            combined = []
            for start in range(0, MIN_REPEATS - size + 1, size):
                members = per_run[start : start + size]
                combined.append({key: combine(kind, [run.get(key) for run in members]) for key in keys})
            disagreement = statistics.fmean(
                base.pair_disagreement([run[key] for run in combined]) for key in keys
            )
            answers = [base.answer_from_items(plan, order, run, groups) for run in combined]
            pairs = list(combinations(answers, 2))
            accuracy = ""
            if gold:
                if kind == "score":
                    hits = [abs(run[key] - gold[key]) <= 0.5 for run in combined for key in gold if run[key] is not None]
                else:
                    hits = [run[key] == gold[key] for run in combined for key in gold]
                accuracy = sum(hits) / len(hits) if hits else ""
            if remedy == "vote3":
                disagree = [
                    sum(per_run[start][key] != per_run[start + 1][key] for key in keys) / len(keys)
                    for start in range(0, MIN_REPEATS - 2, 3)
                ]
                cost = 2 + statistics.fmean(disagree)
            else:
                cost = float(size)
            rows.append(
                {
                    "scenario": scenario,
                    "model": model,
                    "setting": setting,
                    "query_id": query,
                    "remedy": remedy,
                    "combined_runs": len(combined),
                    "items": len(keys),
                    "item_disagreement": disagreement,
                    "answer_reproduction": sum(a == b for a, b in pairs) / len(pairs) if pairs else "",
                    "item_accuracy": accuracy,
                    "labelled_items": len(gold),
                    "calls_per_item": cost,
                }
            )

        minority = Counter()
        for key in keys:
            counts = Counter(run.get(key) for run in per_run).most_common()
            if len(counts) > 1:
                minority[MIN_REPEATS - counts[0][1]] += 1
        MINORITY[(scenario, model, setting, query)] = dict(sorted(minority.items()))

    if not rows:
        print("no cell has", MIN_REPEATS, "clean repeats yet")
        return
    write_outputs(rows)
    with OUT.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    for row in rows:
        print(
            f"{row['scenario']:7s} {row['model'][:24]:24s} Q{row['query_id']:<2d} {row['remedy']:6s} "
            f"runs={row['combined_runs']} disagree={row['item_disagreement']:.4f} repro={row['answer_reproduction']!s:6.6s} "
            f"acc={row['item_accuracy']!s:6.6s} cost={row['calls_per_item']:.2f}"
        )


if __name__ == "__main__":
    main()
