#!/usr/bin/env python3
"""Tables and a figure from experiments/processed/published_repeats/*.csv.

Headline configurations are the ones SemBench's own repeat tables use
(aggregate_table_generator.sf_mappings); medical has only its default
folders. Every other configuration is reported as a robustness check.
"""

from __future__ import annotations

import csv
import json
import statistics
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "experiments" / "processed" / "published_repeats"
TABLES = ROOT / "outputs" / "tables"
FIGURES = ROOT / "outputs" / "figures"
HEADLINE = {
    "movie": "sf2000",
    "animals": "sf200",
    "cars": "sf19672",
    "ecomm": "sf500",
    "mmqa": "sf200",
    "medical": "default",
}
SYSTEMS = ("lotus", "palimpzest", "thalamusdb", "bigquery")
NAMES = {"lotus": "LOTUS", "palimpzest": "Palimpzest", "thalamusdb": "ThalamusDB", "bigquery": "BigQuery"}


def read(name: str) -> list[dict]:
    with (DATA / f"{name}.csv").open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def headline(row: dict) -> bool:
    return HEADLINE.get(row["scenario"]) == row["config"]


def main() -> None:
    cells = [row for row in read("cells") if headline(row)]
    pairs = [row for row in read("pairs") if headline(row)]
    rankings = [row for row in read("scenario_rankings") if headline(row)]
    all_cells = read("cells")
    all_pairs = read("pairs")

    by_system = defaultdict(list)
    for row in cells:
        by_system[row["system"]].append(row)

    lines = [
        "% Generated by scripts/report_published_repeats.py. Do not edit by hand.",
        "\\begin{table}[t]",
        "\\caption{SemBench's published repeats: five executions of each query with Gemini 2.5 Flash, "
        "at the scale factor SemBench uses for its repeat tables. A cell is one system on one query. "
        "Moves is the share of cells whose quality differs across the five runs. Range is the largest "
        "difference between two runs of a cell. Best $-$ mean is how far the luckiest run sits above "
        "the published mean.}",
        "\\label{tab:published}",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{@{}lrrrrr@{}}",
        "\\toprule",
        "System & Cells & Moves & Range $\\ge 0.1$ & Max range & Best $-$ mean \\\\",
        "\\midrule",
    ]

    def summary(rows: list[dict]) -> str:
        ranges = [float(row["range"]) for row in rows]
        gaps = [float(row["best_minus_mean"]) for row in rows]
        moves = sum(value > 1e-9 for value in ranges)
        big = sum(value >= 0.1 for value in ranges)
        return (
            f"{len(rows)} & {moves / len(rows):.0%} & {big / len(rows):.0%} & "
            f"{max(ranges):.2f} & {statistics.fmean(gaps):.3f}"
        ).replace("%", "\\%")

    for system in SYSTEMS:
        if by_system.get(system):
            lines.append(f"{NAMES[system]} & {summary(by_system[system])} \\\\")
    text_rows = [row for row in cells if row["text_only"] == "1"]
    lines += [
        "\\midrule",
        f"Text queries & {summary(text_rows)} \\\\",
        f"All queries & {summary(cells)} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ]

    untied = [row for row in pairs if row["mean_tied"] == "False"]
    reversed_pairs = [row for row in untied if row["any_reversal"] == "True"]
    runs = sum(int(row["repeats"]) for row in untied)
    reversing_runs = sum(int(row["reversals"]) for row in untied)
    all_untied = [row for row in all_pairs if row["mean_tied"] == "False"]
    all_reversed = [row for row in all_untied if row["any_reversal"] == "True"]
    all_moves = sum(float(row["range"]) > 1e-9 for row in all_cells)

    clean = [row for row in cells if int(row["empty_runs"]) == 0]
    text_cells = [row for row in cells if row["text_only"] == "1"]
    text_untied = [row for row in untied if row["text_only"] == "1"]
    text_clean = [row for row in text_cells if int(row["empty_runs"]) == 0]
    facts = {
        "text": {
            "cells": len(text_cells),
            "cells_moving": sum(float(row["range"]) > 1e-9 for row in text_cells),
            "cells_range_01": sum(float(row["range"]) >= 0.1 for row in text_cells),
            "clean_cells": len(text_clean),
            "clean_cells_moving": sum(float(row["range"]) > 1e-9 for row in text_clean),
            "max_range": max(float(row["range"]) for row in text_cells),
            "pairs_untied": len(text_untied),
            "pairs_any_reversal": sum(row["any_reversal"] == "True" for row in text_untied),
            "scenarios": sorted({row["scenario"] for row in text_cells}),
            "queries": len({(row["scenario"], row["query"]) for row in text_cells}),
            "by_scenario": {
                scenario: {
                    "cells": len(rows),
                    "cells_moving": sum(float(row["range"]) > 1e-9 for row in rows),
                }
                for scenario in sorted({row["scenario"] for row in text_cells})
                for rows in [[row for row in text_cells if row["scenario"] == scenario]]
            },
        },
        "cells_with_empty_runs": len(cells) - len(clean),
        "clean_cells": len(clean),
        "clean_cells_moving": sum(float(row["range"]) > 1e-9 for row in clean),
        "clean_cells_range_01": sum(float(row["range"]) >= 0.1 for row in clean),
        "cells": len(cells),
        "cells_moving": sum(float(row["range"]) > 1e-9 for row in cells),
        "cells_range_01": sum(float(row["range"]) >= 0.1 for row in cells),
        "pairs_untied": len(untied),
        "pairs_any_reversal": len(reversed_pairs),
        "single_runs": runs,
        "single_runs_reversing": reversing_runs,
        "scenario_rankings": [
            {
                "scenario": row["scenario"],
                "queries": int(row["common_queries"]),
                "same_order": int(row["repeats_matching_mean_order"]),
                "same_winner": int(row["repeats_matching_mean_winner"]),
                "repeats": int(row["repeats"]),
                "mean_order": row["mean_order"],
            }
            for row in rankings
        ],
        "all_configs": {
            "cells": len(all_cells),
            "cells_moving": all_moves,
            "pairs_untied": len(all_untied),
            "pairs_any_reversal": len(all_reversed),
        },
        "largest_ranges": sorted(
            (
                {
                    "scenario": row["scenario"],
                    "system": row["system"],
                    "query": row["query"],
                    "metric": row["metric"],
                    "values": json.loads(row["values"]),
                }
                for row in cells
            ),
            key=lambda item: -(max(item["values"]) - min(item["values"])),
        )[:8],
    }
    TABLES.mkdir(parents=True, exist_ok=True)
    (TABLES / "published.tex").write_text("\n".join(lines), encoding="utf-8")
    (DATA / "facts.json").write_text(json.dumps(facts, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({key: value for key, value in facts.items() if key != "largest_ranges"}, indent=1))
    for item in facts["largest_ranges"]:
        print(item)

    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        return
    FIGURES.mkdir(parents=True, exist_ok=True)
    figure, axis = plt.subplots(figsize=(3.4, 2.1))
    order = [system for system in SYSTEMS if by_system.get(system)]
    data = [sorted(float(row["range"]) for row in by_system[system]) for system in order]
    for system, values in zip(order, data):
        ys = [1 - index / len(values) for index in range(len(values))]
        axis.step(values, ys, where="post", label=NAMES[system])
    axis.set_xlabel("Range of quality across five runs")
    axis.set_ylabel("Share of cells $\\geq$ x")
    axis.set_yscale("log")
    axis.set_xlim(0, 1)
    axis.legend(fontsize=7, frameon=False)
    figure.tight_layout()
    figure.savefig(FIGURES / "published_ranges.pdf")


if __name__ == "__main__":
    main()
