#!/usr/bin/env python3
"""Tables and facts for the joins, LRO-Bench, UDA-Bench, and product-review repeats.

Reads the processed outputs of analyze_sembench_repeats.py, analyze_lrobench_repeats.py,
and analyze_uda_repeats.py, and the product-review labels. Writes
outputs/tables/{joins,lro_repeats,uda,product}.tex and
experiments/processed/text_suites_facts.json. No model is called.
"""

from __future__ import annotations

import csv
import json
import statistics
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROCESSED = ROOT / "experiments" / "processed"
TABLES = ROOT / "outputs" / "tables"
PRODUCT = ROOT / "experiments" / "raw" / "product-reviews" / "sf10"
FACTS = PROCESSED / "text_suites_facts.json"
NAMES = {
    "managed-gpt-oss-120b": "gpt-oss-120B (M)",
    "managed-llama-3-3-70b-instruct": "Llama-70B (M)",
    "vllm-llama-3-3-70b-instruct": "Llama-70B (V)",
    "vllm-qwen2-5-72b-instruct": "Qwen-72B (V)",
    "managed-mistral-small-3-1-24b-2503": "Mistral-24B (M)",
    "vllm-granite-3-3-8b-instruct": "Granite-8B (V)",
}
HEADER = "% Generated by scripts/report_text_suites.py. Do not edit by hand."


def read(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def pct(value: float, digits: int = 1) -> str:
    return f"{100 * value:.{digits}f}"


def joins(facts: dict) -> None:
    rows = [row for row in read(PROCESSED / "sembench_repeats" / "queries.csv")
            if row["setting"].endswith("_exact_join40")]
    by = {(row["model"], int(row["query_id"])): row for row in rows}
    models = [model for model in NAMES if any(key[0] == model for key in by)]
    models.sort(key=lambda model: statistics.fmean(float(by[(model, q)]["item_flip_rate_k5"]) for q in (5, 6, 7)))
    lines = [HEADER, "\\begin{table}[t]",
             "\\caption{Exact semantic self-joins on 40 reviews (1{,}560 pairs of distinct reviews). "
             "Flip is the share of pairs whose verdict changes across executions (\\%); Repro is answer "
             "reproduction. Q5 and Q6 return the first ten same- and opposite-sentiment pairs, Q7 all opposite-sentiment pairs. "
             "Flip rates are over five executions; for gpt-oss-120B, the expected rate over five of its ten.}",
             "\\label{tab:joins}", "\\small", "\\setlength{\\tabcolsep}{3.5pt}",
             "\\begin{tabular}{@{}lrrrrrrr@{}}", "\\toprule",
             "& \\multicolumn{2}{c}{Q5} & \\multicolumn{2}{c}{Q6} & \\multicolumn{3}{c}{Q7} \\\\",
             "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\\cmidrule(l){6-8}",
             "Deployment & Flip & Repro & Flip & Repro & Flip & Repro & F1 range \\\\", "\\midrule"]
    facts["joins"] = {}
    for model in models:
        cells = []
        entry = {}
        for query in (5, 6, 7):
            row = by[(model, query)]
            quality = json.loads(row["quality_values"])
            cells += [pct(float(row["item_flip_rate_k5"]), 1), f"{float(row['answer_reproduction']):.2f}"]
            entry[query] = {"flip": float(row["item_flip_rate_k5"]), "repro": float(row["answer_reproduction"]),
                            "qmin": min(quality), "qmax": max(quality), "repeats": int(row["repeats"])}
        cells.append(f"{entry[7]['qmax'] - entry[7]['qmin']:.3f}")
        facts["joins"][model] = entry
        lines.append(f"{NAMES[model]} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (TABLES / "joins.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")


LRO_OPERATORS = ["select", "match", "impute", "cluster", "order", "multi"]
LRO_IMPL = {"llm_all": "ALL", "llm_one": "ONE", "llm_semi": "SEMI", "llm_one-simple": "ONE (sort)",
            "llm_one-heap": "ONE (heap)"}
LRO_MODELS = ["managed-gpt-oss-120b", "vllm-llama-3-3-70b-instruct", "managed-llama-3-3-70b-instruct",
              "vllm-granite-3-3-8b-instruct"]


def lrobench(facts: dict) -> None:
    data = json.loads((PROCESSED / "lrobench_repeats" / "facts.json").read_text())
    settings = sorted({key.split("|")[1] for key in data["by_setting"]},
                      key=lambda name: (LRO_OPERATORS.index(name.split("_", 1)[0]), name))
    lines = [HEADER, "\\begin{table*}[t]",
             "\\caption{LRO-Bench, five executions of every scored query in each implementation. Per deployment: "
             "queries with a failed execution, answered queries whose answer differs between executions, and the "
             "mean range of LRO-Bench's quality metric over answered queries. ALL issues one call for the "
             "operand, ONE one call per element, SEMI a hybrid.}",
             "\\label{tab:lro}", "\\small", "\\setlength{\\tabcolsep}{3pt}",
             "\\begin{tabular}{@{}ll" + "rrr" * len(LRO_MODELS) + "@{}}", "\\toprule",
             "& & " + " & ".join(f"\\multicolumn{{3}}{{c}}{{{NAMES[model]}}}" for model in LRO_MODELS) + " \\\\",
             "".join(f"\\cmidrule(lr){{{3 + 3 * index}-{5 + 3 * index}}}" for index in range(len(LRO_MODELS))),
             "Operator & Impl. & " + " & ".join(["Fail", "Differ", "Range"] * len(LRO_MODELS)) + " \\\\",
             "\\midrule"]
    previous = None
    for setting in settings:
        operator, impl = setting.split("_", 1)
        cells = []
        for model in LRO_MODELS:
            value = data["by_setting"].get(f"{model}|{setting}")
            if not value:
                cells += ["--"] * 3
                continue
            spread = value["mean_quality_range"]
            cells += [str(value["queries_any_failure"]),
                      f"{value['answers_differ']}/{value['answered_queries']}",
                      "--" if spread is None or not value["answered_queries"] else f"{spread:.3f}"]
        label = operator.capitalize() if operator != previous else ""
        if previous is not None and operator != previous:
            lines.append("\\addlinespace[2pt]")
        previous = operator
        lines.append(f"{label} & {LRO_IMPL.get(impl, impl)} & " + " & ".join(cells) + " \\\\")
    lines.append("\\midrule")
    cells = []
    for model in LRO_MODELS:
        value = data["by_model"][model]
        cells += [str(value["queries_any_failure"]), f"{value['answers_differ']}/{value['answered_queries']}",
                  f"{value['mean_quality_range']:.3f}"]
    lines += ["All & & " + " & ".join(cells) + " \\\\", "\\bottomrule", "\\end{tabular}", "\\end{table*}"]
    (TABLES / "lro_repeats.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    facts["lro"] = {model: data["by_model"][model] for model in LRO_MODELS}
    by_operator = defaultdict(Counter)
    for key, value in data["by_setting"].items():
        model, setting = key.split("|")
        operator = setting.split("_", 1)[0]
        for field in ("queries", "queries_any_failure", "answered_queries", "answers_differ"):
            by_operator[f"{model}|{operator}"][field] += value[field]
    facts["lro_by_operator"] = {key: dict(value) for key, value in by_operator.items()}
    facts["lro_setting_range"] = {}
    for model in LRO_MODELS:
        shares = [value["answers_differ"] / value["answered_queries"] for key, value in data["by_setting"].items()
                  if key.startswith(f"{model}|") and value["answered_queries"] >= 10]
        facts["lro_setting_range"][model] = {"min": min(shares), "max": max(shares), "settings": len(shares)}
    facts["lro_settings"] = len(settings)


UDA_TASKS = ["Select", "Filter", "Agg", "Join", "Mixed"]
UDA_SHORT = {"Select": "Sel.", "Filter": "Filt.", "Agg": "Agg.", "Join": "Join", "Mixed": "Mix."}
UDA_MODELS = ["managed-gpt-oss-120b", "managed-llama-3-3-70b-instruct", "vllm-granite-3-3-8b-instruct"]


def uda(facts: dict) -> None:
    data = json.loads((PROCESSED / "uda_repeats" / "facts.json").read_text())
    queries = read(PROCESSED / "uda_repeats" / "queries.csv")
    lines = [HEADER, "\\begin{table}[t]",
             "\\caption{UDA-Bench Player, five executions of 123 queries. Values is the share of extracted "
             "(document, attribute) values that change (\\%). Per query class, the number of queries whose "
             "result table differs between executions. F1 is UDA-Bench's quality, mean over queries with a "
             "non-empty ground truth, with the mean range across executions.}",
             "\\label{tab:uda}", "\\small", "\\setlength{\\tabcolsep}{2.2pt}",
             "\\begin{tabular}{@{}lr" + "r" * (len(UDA_TASKS) + 1) + "rr@{}}", "\\toprule",
             "& & \\multicolumn{" + str(len(UDA_TASKS) + 1) + "}{c}{Answers differ} & & \\\\",
             f"\\cmidrule(lr){{3-{3 + len(UDA_TASKS)}}}",
             "Deployment & Values & " + " & ".join(UDA_SHORT[task] for task in UDA_TASKS) + " & All & F1 & Range \\\\",
             "\\midrule"]
    counts = Counter(row["task"] for row in queries if row["model"] == UDA_MODELS[0])
    lines.append("Queries & & " + " & ".join(str(counts[task]) for task in UDA_TASKS)
                 + f" & {sum(counts.values())} & & \\\\")
    lines.append("\\midrule")
    facts["uda"] = {}
    values_by_model = defaultdict(list)
    for row in read(PROCESSED / "uda_repeats" / "items.csv"):
        values_by_model[row["model"]].append(json.loads(row["values"]))
    for model in UDA_MODELS:
        value = data["models"][model]
        extracted = values_by_model[model]
        changed = [runs for runs in extracted if len({str(run) for run in runs}) > 1]
        empty = [runs for runs in changed if any(run in (None, "") for run in runs)]
        between_values = [runs for runs in changed if len({str(run) for run in runs if run not in (None, "")}) > 1]
        null_facts = {"null_flip_share": len(empty) / len(changed) if changed else 0.0,
                      "value_to_value_flip_rate": len(between_values) / len(extracted)}
        rows = [row for row in queries if row["model"] == model]
        differ = Counter(row["task"] for row in rows if int(row["distinct_answers"]) > 1)
        scored = [row for row in rows if row["gold_empty"] == "0" and row["f1_mean"] != ""]
        mean_f1 = statistics.fmean(float(row["f1_mean"]) for row in scored)
        cells = [pct(value["item_flip_rate"], 1)] + [str(differ[task]) for task in UDA_TASKS]
        cells += [str(value["answers_differ"]), f"{mean_f1:.2f}", f"{value['mean_f1_range']:.3f}"]
        lines.append(f"{NAMES[model]} & " + " & ".join(cells) + " \\\\")
        facts["uda"][model] = {**{key: item for key, item in value.items() if key != "attributes"},
                               **null_facts, "mean_f1": mean_f1, "scored_queries": len(scored),
                               "differ_by_task": dict(differ)}
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (TABLES / "uda.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    facts["uda_tasks"] = dict(counts)
    facts["uda_gold_empty"] = sum(row["gold_empty"] == "1" for row in queries if row["model"] == UDA_MODELS[0])


PRODUCT_KIND = {"filter": "Boolean", "map": "map"}


def product(facts: dict) -> None:
    rows = []
    for task_dir in sorted(PRODUCT.iterdir()):
        runs = [json.loads(path.read_text()) for path in sorted(task_dir.glob("repeat-*/labels.json"))]
        labels = [run["labels"] for run in runs]
        keys = sorted(labels[0])
        flips = sum(len({json.dumps(run.get(key), sort_keys=True) for run in labels}) > 1 for key in keys)
        outputs = len({json.dumps(value, sort_keys=True) for run in labels for value in run.values()})
        rows.append({"task": task_dir.name, "operator": runs[0].get("operator", ""), "items": len(keys),
                     "repeats": len(runs), "outputs": outputs, "flips": flips})
    rows.sort(key=lambda row: (row["flips"] / row["items"], row["outputs"]))
    lines = [HEADER, "\\begin{table}[h]",
             "\\caption{Thirteen tasks over the same 100 synthetic product reviews, five executions of "
             "gpt-oss-120B (M). Outputs is the number of distinct outputs over all executions; Flip is the share "
             "of reviews whose output changes.}",
             "\\label{tab:product}", "\\small", "\\begin{tabular}{@{}llrr@{}}", "\\toprule",
             "Task & Operator & Outputs & Flip (\\%) \\\\", "\\midrule"]
    for row in rows:
        name = row["task"].replace("_", " ")
        lines.append(f"{name} & {row['operator']} & {row['outputs']} & {pct(row['flips'] / row['items'], 0)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    (TABLES / "product.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    facts["product"] = rows


def main() -> None:
    facts: dict = {}
    joins(facts)
    lrobench(facts)
    uda(facts)
    product(facts)
    FACTS.write_text(json.dumps(facts, indent=1, default=str))
    print(f"tables joins, lro_repeats, uda, product -> {TABLES.relative_to(ROOT)}; facts -> {FACTS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
