#!/usr/bin/env python3
"""Cause probes: one factor of the execution environment varied at a time.

Reads items.csv and queries.csv from analyze_sembench_repeats.py, restricted
to settings tagged "probe". For each setting and query it reports the item
flip rate within the setting, the share of items whose majority output differs
from the reference setting, and the mean quality.

Writes outputs/tables/probes.tex and experiments/processed/sembench_repeats/probes.json.
"""

from __future__ import annotations

import csv
import json
import random
import statistics
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "experiments" / "processed" / "sembench_repeats"
TABLE = ROOT / "outputs" / "tables" / "probes.tex"
PROBES = [
    ("vllm-granite-3-3-8b-instruct", "w1_lp_probe", "Concurrency 1"),
    ("vllm-granite-3-3-8b-instruct", "w8_lp_probe", "Concurrency 8"),
    ("vllm-granite-3-3-8b-instruct", "w20_lp_probe", "Concurrency 20 (ref.)"),
    ("vllm-granite-3-3-8b-instruct", "w64_lp_probe", "Concurrency 64"),
    ("vllm-granite-3-3-8b-instruct", "w20_shuffle_lp_probe", "Shuffled input order"),
    ("managed-gpt-oss-120b", "w20_r-low_probe", "Reasoning effort low"),
    ("managed-gpt-oss-120b", "w20_r-medium_probe", "Reasoning effort medium (ref.)"),
    ("managed-gpt-oss-120b", "w20_r-high_probe", "Reasoning effort high"),
]
REFERENCE = {
    "vllm-granite-3-3-8b-instruct": "w20_lp_probe",
    "managed-gpt-oss-120b": "w20_r-medium_probe",
}
QUERIES = (3, 8, 9)


def read(name: str) -> list[dict]:
    with (DATA / f"{name}.csv").open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


SEED = 17
BOOTSTRAP = 2000


def majority(values: list) -> str:
    values = [str(value) for value in values]
    return max(sorted(set(values)), key=values.count)


def disagreement(values: list) -> float:
    values = [str(value) for value in values]
    k = len(values)
    same = sum(values.count(value) * (values.count(value) - 1) for value in set(values)) / (k * (k - 1))
    return 1.0 - same


def main() -> None:
    queries = {(row["model"], row["setting"], int(row["query_id"])): row for row in read("queries") if row["scenario"] == "movie"}
    items = defaultdict(dict)
    for row in read("items"):
        if row["scenario"] == "movie" and row["setting"].endswith("_probe"):
            items[(row["model"], row["setting"], int(row["query_id"]))][row["item"]] = json.loads(row["values"])

    rng = random.Random(SEED)
    results = []
    for model, setting, label in PROBES:
        entry = {"model": model, "setting": setting, "label": label, "queries": {}}
        # Paired bootstrap over items, pooled over queries, of the difference in
        # pairwise disagreement between this setting and the reference.
        paired = []
        for query in QUERIES:
            own = items.get((model, setting, query), {})
            reference = items.get((model, REFERENCE[model], query), {})
            for key in own:
                if key in reference:
                    paired.append(disagreement(own[key]) - disagreement(reference[key]))
        if paired and setting != REFERENCE[model]:
            draws = sorted(
                statistics.fmean(rng.choice(paired) for _ in paired) for _ in range(BOOTSTRAP)
            )
            entry["difference"] = statistics.fmean(paired)
            entry["difference_ci"] = [draws[int(0.025 * BOOTSTRAP)], draws[int(0.975 * BOOTSTRAP) - 1]]
        for query in QUERIES:
            row = queries.get((model, setting, query))
            if not row:
                continue
            own = items.get((model, setting, query), {})
            reference = items.get((model, REFERENCE[model], query), {})
            shared = [key for key in own if key in reference]
            moved = sum(majority(own[key]) != majority(reference[key]) for key in shared)
            quality = json.loads(row["quality_values"]) if row["quality_values"] else []
            entry["queries"][query] = {
                "repeats": int(row["repeats"]),
                "flip_rate": float(row["item_flip_rate"]),
                "pair_disagreement": float(row["item_pair_disagreement"]),
                "majority_moved": moved / len(shared) if shared else None,
                "quality_mean": statistics.fmean(quality) if quality else None,
                "answer_reproduction": float(row["answer_reproduction"]),
            }
        results.append(entry)

    lines = [
        "% Generated by scripts/report_probes.py. Do not edit by hand.",
        "\\begin{table*}[t]",
        "\\caption{Cause probes on Movie Q3, Q8, and Q9. Each setting changes one factor. Disagreement is the pairwise "
        "item disagreement within the setting (\\%); moved is the share of items whose majority output differs from the "
        "reference setting of the same model (\\%); repeats in parentheses.}",
        "\\label{tab:probes}",
        "\\small",
        "\\begin{tabular}{@{}l" + "rr" * len(QUERIES) + "r@{}}",
        "\\toprule",
        "& " + " & ".join(f"\\multicolumn{{2}}{{c}}{{Movie Q{query}}}" for query in QUERIES) + " & Pooled \\\\",
        " ".join(f"\\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(len(QUERIES))),
        "Setting & " + " & ".join("Disagree & Moved" for _ in QUERIES) + " & $\\Delta$ disagree [95\\% CI] \\\\",
        "\\midrule",
    ]
    previous_model = None
    for entry in results:
        if previous_model and entry["model"] != previous_model:
            lines.append("\\midrule")
        previous_model = entry["model"]
        cells = []
        for query in QUERIES:
            value = entry["queries"].get(query)
            if not value:
                cells += ["--", "--"]
                continue
            cells.append(f"{100 * value['pair_disagreement']:.2f} ({value['repeats']})")
            moved = value["majority_moved"]
            cells.append("--" if moved is None or entry["setting"] == REFERENCE[entry["model"]] else f"{100 * moved:.1f}")
        if "difference" in entry:
            low, high = entry["difference_ci"]
            cells.append(f"{100 * entry['difference']:+.2f} [{100 * low:+.2f}, {100 * high:+.2f}]")
        else:
            cells.append("--")
        model_label = "Granite-8B" if "granite" in entry["model"] else "gpt-oss-120B"
        lines.append(f"{model_label}: {entry['label']} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    TABLE.write_text("\n".join(lines), encoding="utf-8")
    (DATA / "probes.json").write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    for entry in results:
        print(entry["label"], {query: {k: (round(v, 4) if isinstance(v, float) else v) for k, v in value.items()} for query, value in entry["queries"].items()})


if __name__ == "__main__":
    main()
